const { test } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID, randomBytes } = require('crypto');
const jwt = require('jsonwebtoken');
const sharp = require('sharp');
if (!process.env.DATABASE_URL?.includes('/corallink_verify_')) throw new Error('Use an isolated corallink_verify_ database');
process.env.JWT_SECRET = randomBytes(32).toString('hex');
const prisma = require('../src/config/prisma');
const app = require('../src/server');
test('publishing, milestone concurrency, private proofs, role authorization and payment accounting', async () => {
 const server = app.listen(0, '127.0.0.1'); await new Promise(r => server.once('listening', r));
 const base = `http://127.0.0.1:${server.address().port}`;
 const admin = await prisma.user.create({ data: { nama: 'Test admin', email: 'admin@example.invalid', password: randomBytes(32).toString('hex'), role: 'admin' } });
 const investor = await prisma.user.create({ data: { nama: 'Test investor', email: 'investor@example.invalid', password: randomBytes(32).toString('hex'), role: 'investor' } });
 const other = await prisma.user.create({ data: { nama: 'Other investor', email: 'other@example.invalid', password: randomBytes(32).toString('hex'), role: 'investor' } });
 const token = u => jwt.sign({ id: u.id, role: u.role }, process.env.JWT_SECRET);
 const call = (url, method = 'GET', user, body) => fetch(base + url, { method, headers: { ...(user ? { Authorization: `Bearer ${token(user)}` } : {}), ...(body && !(body instanceof FormData) ? { 'Content-Type':'application/json' } : {}) }, body: body instanceof FormData ? body : body ? JSON.stringify(body) : undefined });
 const image = await sharp({ create: { width: 20, height: 20, channels: 3, background: '#ffffff' } }).png().toBuffer();
 const ml = require('http').createServer((req,res) => { res.setHeader('Content-Type','application/json'); res.end(JSON.stringify({predicted_class:'Bleached',confidence:99})); }).listen(0,'127.0.0.1');
 await new Promise(r=>ml.once('listening',r)); process.env.AI_SERVICE_URL = `http://127.0.0.1:${ml.address().port}/predict`;
 const form = (buffer = image) => { const f = new FormData(); f.append('image', new Blob([buffer], { type:'image/png' }), 'image.png'); f.append('namaProyek', 'Test reef'); f.append('lokasi', 'Test location'); f.append('description', 'Full project description'); f.append('species', 'Acropora'); f.append('fundingTarget', '100000'); return f; };
 try {
  const photoForm = buffer => { const f = new FormData(); f.append('image',new Blob([buffer],{type:'image/png'}),'avatar.png'); return f; };
  assert.equal((await call('/api/auth/profile/photo')).status,401);
  assert.equal((await call('/api/auth/profile/photo','POST',null,photoForm(image))).status,401);
  assert.equal((await call('/api/auth/profile/photo','GET',investor)).status,204);
  assert.equal((await call('/api/auth/profile/photo','POST',investor,photoForm(Buffer.from('invalid')))).status,400);
  assert.equal((await call(`/api/auth/profile/photo?userId=${other.id}`,'POST',investor,photoForm(image))).status,200);
  const photoResponse = await call('/api/auth/profile/photo','GET',investor);
  assert.equal(photoResponse.headers.get('cache-control'),'private, no-store');
  const photo = Buffer.from(await photoResponse.arrayBuffer());
  assert.equal((await sharp(photo).metadata()).format,'webp');
  assert.equal((await call('/api/auth/profile/photo','GET',other)).status,204);
  assert.equal((await call(`/uploads/avatars/${investor.id}.webp`)).status,404);
  assert.equal((await call('/api/auth/profile/photo','POST',investor,photoForm(Buffer.from('invalid')))).status,400);
  assert.deepEqual(Buffer.from(await (await call('/api/auth/profile/photo','GET',investor)).arrayBuffer()),photo);
  const largeImage = await sharp({create:{width:1200,height:800,channels:3,background:'#123456'}}).png().toBuffer();
  assert.equal((await call('/api/auth/profile/photo','POST',investor,photoForm(largeImage))).status,200);
  const resized = await sharp(Buffer.from(await (await call('/api/auth/profile/photo','GET',investor)).arrayBuffer())).metadata();
  assert.equal(resized.width,512);
  assert.equal((await call('/api/projects','POST', null, {})).status,401);
  assert.equal((await call('/api/projects','POST', investor, {})).status,403);
  assert.equal((await call('/api/projects','POST', admin, {})).status,400);
  assert.equal((await call('/api/projects','POST', admin, form(Buffer.from('not an image')))).status,400);
  const response = await call('/api/projects','POST',admin,form()); assert.equal(response.status,201); const project = (await response.json()).data;
  assert.equal(project.description,'Full project description'); assert.equal(project.milestones.length,4);
  assert.equal((await call(project.imageUrl)).status,200);
  assert.equal((await call(`/api/projects/${project.id}`)).status,200);
  const milestone = { version:0, milestones:[{phase:'Phase 1',title:'Assessment',status:'Complete'}], progressNote:'Completed field assessment' };
  assert.equal((await call(`/api/projects/${project.id}/milestones`,'PUT',investor,milestone)).status,403);
  assert.equal((await call(`/api/projects/${project.id}/milestones`,'PUT',admin,milestone)).status,200);
  assert.equal((await call(`/api/projects/${project.id}/milestones`,'PUT',admin,milestone)).status,409);
  const legacyCount = await prisma.donation.count();
  assert.equal((await call('/api/donations', 'POST', investor, { projectId: project.id, jumlahDonasi: 25000 })).status, 410);
  assert.equal(await prisma.donation.count(), legacyCount, 'Retired endpoint must not write donation records');
  const legacy = await prisma.donation.create({ data: { projectId: project.id, investorId: investor.id, jumlahDonasi: 1000 } });
  assert.equal((await (await call('/api/donations/saya', 'GET', investor)).json()).data[0].id, legacy.id);
  assert.deepEqual((await (await call('/api/donations/saya', 'GET', other)).json()).data, []);
  const payload = { projectId:project.id, amount:25000, idempotencyKey:randomUUID(), status:'Completed' };
  process.env.QRIS_IMAGE_PATH = '/nonexistent-qris-test.png';
  assert.equal((await call('/api/transactions','POST',investor,payload)).status,503);
  assert.equal((await (await call('/api/payments/settings')).json()).data.enabled,false);
  delete process.env.QRIS_IMAGE_PATH;
  const settings = (await (await call('/api/payments/settings')).json()).data;
  assert.equal(settings.enabled,true); assert.equal(settings.bankEnabled,false);
  const qr = await call(settings.qrisImageUrl); assert.equal(qr.status,200);
  assert.deepEqual(Buffer.from(await qr.arrayBuffer()),require('fs').readFileSync(require('../src/utils/paymentSettings').qrisPath()));
  const qrisRequest = await call('/api/transactions','POST',investor,payload);
  assert.equal(qrisRequest.status,201);
  assert.equal((await qrisRequest.json()).data.status,'AwaitingProof');
  const account = { bankName:'TEST ONLY', accountNumber:'00000000', accountHolder:'TEST ONLY' };
  assert.equal((await call('/api/payments/settings','PUT',investor,account)).status,403);
  assert.equal((await call('/api/payments/settings','PUT',admin,account)).status,200);
  const transaction = (await (await call('/api/transactions','POST',investor,payload)).json()).data;
  assert.equal(transaction.status,'AwaitingProof');
  assert.equal((await (await call('/api/transactions','POST',investor,payload)).json()).data.id,transaction.id);
  assert.equal((await call(`/api/transactions/${transaction.id}`,'GET',other)).status,404);
  // A draft must never be treated as a submitted or verified payment.
  const draft = await prisma.transaction.findUnique({ where: { id: transaction.id } });
  assert.equal(draft.proofFile, null);
  assert.deepEqual((await (await call('/api/transactions', 'GET', admin)).json()).data, [], 'Drafts are not payment submissions');
  assert.equal((await (await call('/api/transactions/me', 'GET', investor)).json()).data[0].id, transaction.id, 'Investors can resume drafts');
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`, 'POST', investor, {})).status, 400);
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`, 'POST', investor, photoForm(Buffer.from('not an image')))).status, 400);
  const emptyProof = new FormData(); emptyProof.append('image', new Blob([], { type: 'image/png' }), 'empty.png');
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`, 'POST', investor, emptyProof)).status, 400);
  assert.equal((await call(`/api/transactions/${transaction.id}/status`, 'PUT', investor, { status: 'Completed' })).status, 403);
  assert.equal((await call(`/api/transactions/${transaction.id}/status`, 'PUT', admin, { status: 'Completed' })).status, 409);
  assert.equal((await prisma.transaction.findUnique({ where: { id: transaction.id } })).status, 'AwaitingProof');
  assert.equal((await (await call(`/api/projects/${project.id}`)).json()).data.fundingRaised, '0');
  const proof = new FormData(); proof.append('image',new Blob([image],{type:'image/png'}),'proof.png');
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`,'POST',investor,proof)).status,200);
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`,'GET',other)).status,404);
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`,'GET')).status,401);
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`,'GET',admin)).status,200);
  const submissions = (await (await call('/api/transactions', 'GET', admin)).json()).data;
  assert.equal(submissions.length, 1); assert.equal(submissions[0].id, transaction.id); assert.equal(submissions[0].hasProof, true);
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`, 'POST', investor, proof)).status, 409);
  assert.equal((await call(`/api/transactions/${transaction.id}/status`, 'PUT', admin, { status: 'Failed', note: 'Please upload the correct proof' })).status, 200);
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`, 'POST', investor, {})).status, 400);
  assert.equal((await prisma.transaction.findUnique({ where: { id: transaction.id } })).status, 'Failed');
  assert.equal((await call(`/api/transactions/${transaction.id}/proof`, 'POST', investor, proof)).status, 200);
  const stored = await prisma.transaction.findUnique({where:{id:transaction.id}});
  assert.equal((await call('/uploads/private/'+stored.proofFile)).status,404);
  assert.equal((await (await call(`/api/projects/${project.id}`)).json()).data.fundingRaised,'0');
  assert.equal((await call(`/api/transactions/${transaction.id}/status`,'PUT',investor,{status:'Completed'})).status,403);
  assert.equal((await call(`/api/transactions/${transaction.id}/status`,'PUT',admin,{status:'Completed'})).status,200);
  assert.equal((await call(`/api/transactions/${transaction.id}/status`,'PUT',admin,{status:'Completed'})).status,409);
  assert.equal((await (await call(`/api/projects/${project.id}`)).json()).data.fundingRaised,'25000');
  assert.equal((await (await call('/api/transactions/me','GET',investor)).json()).data.length,1);
  await prisma.user.update({where:{id:admin.id},data:{role:'investor'}});
  assert.equal((await call('/api/projects','POST',admin,form())).status,403);
 } finally { await new Promise(r => ml.close(r)); await new Promise(r => server.close(r)); await prisma.$disconnect(); }
});
